#!/usr/bin/env python3
"""Generate the matrix-multiply data file (`programs/matmul.dmem`) and
expected output (`programs/matmul.expect`) for an N×N byte matrix
multiply with elements in 0..15.

Memory layout (matches matmul_mm{a,b,c}.S):

    A: 0x2000 + i*N + j   (N*N bytes)
    B: 0x3000 + i*N + j
    C: 0x4000 + i*N + j   (zero on entry)

C is checked word-by-word at 0x4000..0x4000+N*N.  Element 0..255 wrap
around because `sb` truncates to one byte; the expected matrix is
computed mod 256.
"""
from __future__ import annotations

import argparse
import random
from pathlib import Path

from cache_lab_common import find_repo


def gen_matrix(n: int, seed: int) -> list[list[int]]:
    rng = random.Random(seed)
    return [[rng.randint(0, 15) for _ in range(n)] for _ in range(n)]


def matmul_mod256(A, B, n) -> list[list[int]]:
    C = [[0] * n for _ in range(n)]
    for i in range(n):
        for k in range(n):
            aik = A[i][k]
            if aik == 0:
                continue
            for j in range(n):
                C[i][j] = (C[i][j] + aik * B[k][j]) & 0xFF
    return C


def write_dmem(out: Path, A, B, n: int) -> None:
    # The shared .dmem is loaded at base 0x2000 in the testbench.
    # We need bytes from 0x2000..(0x4000+N*N).  Region between matrices
    # is filler 0x00.  Load order: A at [0x0..N*N), then 0x1000 .. 0x1000+N*N B,
    # then 0x2000 .. 0x2000+N*N C (zeros).
    size = 0x2000 + n * n  # offset 0x4000 in absolute, minus base 0x2000
    bytes_ = [0] * size
    # A at offset 0
    for i in range(n):
        for j in range(n):
            bytes_[i * n + j] = A[i][j]
    # B at offset 0x1000 (4096)
    for i in range(n):
        for j in range(n):
            bytes_[0x1000 + i * n + j] = B[i][j]
    # C left at zero
    lines = [f"{b:02x}" for b in bytes_]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_expect(out: Path, C, n: int) -> None:
    # The testbench peeks one word per line: "addr  word".  C lives at
    # 0x4000.  Pack four bytes little-endian into each 32-bit word.
    rows = []
    for word_idx in range(n * n // 4):
        addr = 0x4000 + word_idx * 4
        b0 = C[(word_idx * 4 + 0) // n][(word_idx * 4 + 0) % n]
        b1 = C[(word_idx * 4 + 1) // n][(word_idx * 4 + 1) % n]
        b2 = C[(word_idx * 4 + 2) // n][(word_idx * 4 + 2) % n]
        b3 = C[(word_idx * 4 + 3) // n][(word_idx * 4 + 3) % n]
        word = (b3 << 24) | (b2 << 16) | (b1 << 8) | b0
        rows.append(f"{addr:08x} {word:08x}")
    out.write_text("\n".join(rows) + "\n", encoding="utf-8")


def stride_shift(n: int) -> int:
    """slli shift amount for stride = N bytes (N must be a power of two)."""
    if n & (n - 1):
        raise ValueError(f"matrix dim {n} must be a power of two")
    return n.bit_length() - 1


MMA_TEMPLATE = """.text
# {N}x{N} byte matrix multiply, ijk loop order (MMA).
#   A at 0x2000, B at 0x3000, C at 0x4000.  Generated by
#   scripts/generate_matmul.py — DO NOT EDIT BY HAND.

_start:
    lui  sp, 0xC
    lui  s0, 0x2          # A = 0x2000
    lui  s1, 0x3          # B = 0x3000
    lui  s2, 0x4          # C = 0x4000
    addi s3, x0, {N}

    addi s4, x0, 0
i_loop:
    bge  s4, s3, mm_end
    addi s5, x0, 0
j_loop:
    bge  s5, s3, j_end
    addi s6, x0, 0
    addi s7, x0, 0
k_loop:
    bge  s7, s3, k_end
    slli t0, s4, {SH}
    add  t0, t0, s7
    add  t0, s0, t0
    lb   a0, 0(t0)
    slli t1, s7, {SH}
    add  t1, t1, s5
    add  t1, s1, t1
    lb   a1, 0(t1)
    jal  ra, mul
    add  s6, s6, a0
    addi s7, s7, 1
    jal  x0, k_loop
k_end:
    slli t0, s4, {SH}
    add  t0, t0, s5
    add  t0, s2, t0
    sb   s6, 0(t0)
    addi s5, s5, 1
    jal  x0, j_loop
j_end:
    addi s4, s4, 1
    jal  x0, i_loop
mm_end:
    ebreak

mul:
    addi t6, x0, 0
    andi a1, a1, 0xff
    beq  a1, x0, mul_done
mul_loop:
    add  t6, t6, a0
    addi a1, a1, -1
    bne  a1, x0, mul_loop
mul_done:
    add  a0, t6, x0
    jalr x0, 0(ra)
"""


MMB_TEMPLATE = """.text
# {N}x{N} byte matrix multiply, ikj loop order (MMB).
#   A at 0x2000, B at 0x3000, C at 0x4000.  Generated by
#   scripts/generate_matmul.py — DO NOT EDIT BY HAND.

_start:
    lui  sp, 0xC
    lui  s0, 0x2
    lui  s1, 0x3
    lui  s2, 0x4
    addi s3, x0, {N}

    addi t0, x0, 0
    addi t1, x0, {N_SQR}
zero_c:
    bge  t0, t1, zero_done
    add  t2, s2, t0
    sb   x0, 0(t2)
    addi t0, t0, 1
    jal  x0, zero_c
zero_done:

    addi s4, x0, 0
i_loop:
    bge  s4, s3, mm_end
    addi s7, x0, 0
k_loop:
    bge  s7, s3, k_end
    slli t0, s4, {SH}
    add  t0, t0, s7
    add  t0, s0, t0
    lb   s8, 0(t0)
    addi s5, x0, 0
j_loop:
    bge  s5, s3, j_end
    slli t1, s7, {SH}
    add  t1, t1, s5
    add  t1, s1, t1
    lb   a1, 0(t1)
    add  a0, s8, x0
    jal  ra, mul
    slli t0, s4, {SH}
    add  t0, t0, s5
    add  t0, s2, t0
    lb   t2, 0(t0)
    add  t2, t2, a0
    sb   t2, 0(t0)
    addi s5, s5, 1
    jal  x0, j_loop
j_end:
    addi s7, s7, 1
    jal  x0, k_loop
k_end:
    addi s4, s4, 1
    jal  x0, i_loop
mm_end:
    ebreak

mul:
    addi t6, x0, 0
    andi a1, a1, 0xff
    beq  a1, x0, mul_done
mul_loop:
    add  t6, t6, a0
    addi a1, a1, -1
    bne  a1, x0, mul_loop
mul_done:
    add  a0, t6, x0
    jalr x0, 0(ra)
"""


MMC_TEMPLATE = """.text
# {N}x{N} byte matrix multiply, blocked (MMC) with block size {B}.
#   A at 0x2000, B at 0x3000, C at 0x4000.  Generated by
#   scripts/generate_matmul.py — DO NOT EDIT BY HAND.

_start:
    lui  sp, 0xC
    lui  s0, 0x2
    lui  s1, 0x3
    lui  s2, 0x4
    addi s3, x0, {N}
    addi s11, x0, {B}

    addi t0, x0, 0
    addi t1, x0, {N_SQR}
zero_c:
    bge  t0, t1, zero_done
    add  t2, s2, t0
    sb   x0, 0(t2)
    addi t0, t0, 1
    jal  x0, zero_c
zero_done:

    addi s4, x0, 0
ii_loop:
    bge  s4, s3, mm_end
    add  t3, s4, s11
    addi s5, x0, 0
jj_loop:
    bge  s5, s3, jj_end
    add  t4, s5, s11
    addi s7, x0, 0
kk_loop:
    bge  s7, s3, kk_end
    add  t5, s7, s11
    add  s8, s4, x0
i_loop:
    bge  s8, t3, i_end
    add  s9, s5, x0
j_loop:
    bge  s9, t4, j_end
    add  s10, s7, x0
    slli t0, s8, {SH}
    add  t0, t0, s9
    add  t0, s2, t0
    lb   gp, 0(t0)
k_loop:
    bge  s10, t5, k_end
    slli t1, s8, {SH}
    add  t1, t1, s10
    add  t1, s0, t1
    lb   a0, 0(t1)
    slli t2, s10, {SH}
    add  t2, t2, s9
    add  t2, s1, t2
    lb   a1, 0(t2)
    jal  ra, mul
    add  gp, gp, a0
    addi s10, s10, 1
    jal  x0, k_loop
k_end:
    sb   gp, 0(t0)
    addi s9, s9, 1
    jal  x0, j_loop
j_end:
    addi s8, s8, 1
    jal  x0, i_loop
i_end:
    add  s7, s7, s11
    jal  x0, kk_loop
kk_end:
    add  s5, s5, s11
    jal  x0, jj_loop
jj_end:
    add  s4, s4, s11
    jal  x0, ii_loop
mm_end:
    ebreak

mul:
    addi t6, x0, 0
    andi a1, a1, 0xff
    beq  a1, x0, mul_done
mul_loop:
    add  t6, t6, a0
    addi a1, a1, -1
    bne  a1, x0, mul_loop
mul_done:
    add  a0, t6, x0
    jalr x0, 0(ra)
"""


def write_assembly(programs_dir: Path, n: int, block: int) -> None:
    sh = stride_shift(n)
    nsq = n * n
    (programs_dir / "matmul_mma.S").write_text(
        MMA_TEMPLATE.format(N=n, SH=sh), encoding="utf-8"
    )
    (programs_dir / "matmul_mmb.S").write_text(
        MMB_TEMPLATE.format(N=n, SH=sh, N_SQR=nsq), encoding="utf-8"
    )
    (programs_dir / "matmul_mmc.S").write_text(
        MMC_TEMPLATE.format(N=n, SH=sh, N_SQR=nsq, B=block), encoding="utf-8"
    )
    print(f"Wrote matmul_mm{{a,b,c}}.S for {n}x{n} (MMC block={block})")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--n", type=int, default=32, help="Matrix dimension (power of 2)")
    parser.add_argument("--block", type=int, default=8, help="MMC block size")
    parser.add_argument("--seed", type=int, default=20260514, help="RNG seed")
    parser.add_argument(
        "--repo", type=Path,
        help="Target CPU_Lab2-style repository. Defaults to CACHE_LAB_REPO or cwd parent search.",
    )
    parser.add_argument("--dmem", type=Path)
    parser.add_argument("--expect", type=Path)
    parser.add_argument(
        "--programs-dir", type=Path,
        help="Where to write the matmul_mm{a,b,c}.S sources",
    )
    parser.add_argument(
        "--skip-asm", action="store_true",
        help="Only regenerate .dmem and .expect, leave .S files alone",
    )
    args = parser.parse_args()
    repo = find_repo(args.repo)
    dmem = args.dmem or (repo / "programs" / "matmul.dmem")
    expect = args.expect or (repo / "programs" / "matmul.expect")
    programs_dir = args.programs_dir or (repo / "programs")
    dmem.parent.mkdir(parents=True, exist_ok=True)
    expect.parent.mkdir(parents=True, exist_ok=True)
    programs_dir.mkdir(parents=True, exist_ok=True)

    A = gen_matrix(args.n, args.seed)
    B = gen_matrix(args.n, args.seed + 1)
    C = matmul_mod256(A, B, args.n)

    write_dmem(dmem, A, B, args.n)
    write_expect(expect, C, args.n)
    print(
        f"Wrote {dmem} ({args.n*args.n} bytes A + {args.n*args.n} bytes B)"
    )
    print(f"Wrote {expect} ({args.n*args.n//4} expected words at 0x4000)")
    if not args.skip_asm:
        write_assembly(programs_dir, args.n, args.block)


if __name__ == "__main__":
    main()
